name: Hoi Quan Update VIP
on:
  schedule:
    - cron: '*/20 * * * *' # Cứ 20 phút tự quét lấy link 1 lần
  workflow_dispatch:      # Nút bấm để Mạnh chạy tay bất cứ lúc nào
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Quyền cực quan trọng để ghi đè file list.m3u
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Hoi Quan Script
        run: python get_link.py

      - name: Deploy to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add list.m3u
          # Nếu không có trận mới thì không báo lỗi, vẫn tính là Success
          git commit -m "Update list Hoi Quan VIP" || exit 0
          git push
